spring.application.name=new_syria

spring.datasource.url=jdbc:postgresql://centerbeam.proxy.rlwy.net:39375/railway

spring.datasource.username=postgres
spring.datasource.password=TRbJupgCQnIMAlkGODZWBihxaeCEQCAU

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.mail=DEBUG



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mostafa.mahmoudegy10@gmail.com
spring.mail.password=mwms xlmo tokw wffb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# Core Spring Security debug info (logins, decisions, etc.)
logging.level.org.springframework.security=DEBUG

# Authentication details (username, authorities)
logging.level.org.springframework.security.authentication=DEBUG

# Authorization decisions
logging.level.org.springframework.security.access=DEBUG

# Hide the extremely verbose TRACE logs unless needed
logging.level.org.springframework.security.web.access=INFO
